<a href="https://colab.research.google.com/github/Sritam33/Numpy/blob/main/numpy_pratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
a.shape
a.reshape(-1,1)
print(a)
b.reshape(-1,1)
c.reshape(-1,1)

[1 2 3]


array([[7],
       [8],
       [9]])

In [5]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

# Create three arrays of shape (3,)
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

# Concatenate along the column axis
result = np.concatenate((array1, array2, array3), axis=0)
print(result)

# Reshape the result to make it a column vector
result = result.reshape((3, -1))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nArray 3:")
print(array3)

print("\nConcatenated Result:")
print(result)


In [ ]:
a=np.arange(3)
b=np.arange(3)
c=np.arange(3)
d=np.concatenate((a,b,c),axis =1)

In [ ]:
d

In [ ]:
arr = np.arange(50)
arr

In [ ]:
for i in arr:
  if (i % 2 != 0):
    print(i)

In [ ]:
a=np.random.random(100,)
a

In [ ]:
np.mean(a)

In [ ]:
np.std(a)

In [ ]:
anormalized= (a - np.mean(a))/np.std(a)

In [ ]:
b=np.random.random(20,)

In [ ]:
np.mean(b)

In [ ]:
np.median(b)

In [ ]:
np.mode(b)

In [ ]:
a= np.arange(40)
b = a.reshape((8,5))
b

In [ ]:
A=np.random.randint((24),size=(4,6))

In [ ]:
A

In [ ]:
A[2,3]

In [ ]:
a1=np.random.randint(1,500,size=100)
a1

In [ ]:
np.argmax(a1)

In [ ]:
np.max(a1)

In [ ]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
np.vstack((a,b))

In [ ]:
np.__version__

In [ ]:
arr=np.random.randint(5,60,size=(20,30))
arr
np.vsplit(arr,4)

In [ ]:
a=np.arange(3)
a.shape

In [ ]:
a.ndim

In [ ]:
b=a.reshape(3,1)
b.shape

In [ ]:
a= np.arange(6).reshape(2,3)
b=a[:,np.newaxis,:]
b.shape

In [ ]:
list=[i for i in range(1,21)]

In [ ]:
list

In [ ]:
a1=np.array([i for i in list if (i % 2 ==0)])




In [ ]:
a1

In [ ]:
a2=np.array([i for i in list if (i % 2 !=0)])


In [ ]:
a2

In [ ]:
a1=np.array([list])

In [ ]:
b=a1[a1%2==0]
b

In [ ]:
b =a1[a1%2 != 0]
b

In [ ]:
b=np.random.random(80).reshape(8,10)

In [ ]:
np.sum(b>0.5)


In [ ]:
c=b [b>0.5]
c